services:
    kibako-db:
        container_name: kibako-db
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - db_data_volume:/var/lib/postgresql/data

volumes:
    db_data_volume:
